/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Attila' at '8/10/16 7:37 PM' with Gradle 2.6
 *
 * @author Attila, @date 8/10/16 7:37 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
